@server = http://localhost:3000

# @server = https://street-easy.onrender.com/


### Send email
POST {{api}}/send-email
Content-Type: application/json

{
    "email": "string@email.com",
}

### Sendcode
PATCH {{api}}/send-code
Content-Type: application/json

{
  "code" : 567094
}

